version: '3'
services:
  app:
    build: .
    env_file:
      - .env

    ports:
      - "3010:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

    volumes:
      - db-data:/var/lib/mysql

  volumes:
    db-data:
      driver: local