"""device and user schemas and relationship

Revision ID: 31d01c97580a
Revises: c64651f96f13
Create Date: 2025-05-09 12:57:45.355190

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "31d01c97580a"
down_revision: Union[str, None] = "c64651f96f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Fill in default for existing NULLs
    op.execute("UPDATE auth_user_devices SET is_mobile = 0 WHERE is_mobile IS NULL")
    op.execute("UPDATE auth_user_devices SET is_bot = 0 WHERE is_bot IS NULL")
    op.execute("UPDATE auth_user_devices SET is_pc = 0 WHERE is_pc IS NULL")
    op.execute("UPDATE auth_user_devices SET is_tablet = 0 WHERE is_tablet IS NULL")

    op.add_column(
        "auth_user_devices",
        sa.Column("device_fingerprint", sa.String(length=64), nullable=False),
    )
    op.alter_column(
        "auth_user_devices",
        "is_mobile",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "auth_user_devices",
        "is_tablet",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "auth_user_devices",
        "is_pc",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "auth_user_devices",
        "is_bot",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.drop_index("ix_auth_user_devices_ip_address", table_name="auth_user_devices")
    op.drop_index("uq_user_device", table_name="auth_user_devices")
    op.create_index(
        op.f("ix_auth_user_devices_device_fingerprint"),
        "auth_user_devices",
        ["device_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_user_devices_os_name"),
        "auth_user_devices",
        ["os_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_user_devices_os_version"),
        "auth_user_devices",
        ["os_version"],
        unique=False,
    )
    op.create_unique_constraint(
        "unique_user_device_fingerprint",
        "auth_user_devices",
        ["user_id", "device_fingerprint"],
    )
    op.drop_constraint(
        "auth_user_devices_ibfk_1", "auth_user_devices", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "auth_user_devices", "auth_users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("auth_user_devices", "device_type")
    op.drop_column("auth_user_devices", "ip_address")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_user_devices",
        sa.Column("ip_address", mysql.VARCHAR(length=45), nullable=False),
    )
    op.add_column(
        "auth_user_devices",
        sa.Column("device_type", mysql.VARCHAR(length=20), nullable=True),
    )
    op.drop_constraint(None, "auth_user_devices", type_="foreignkey")
    op.create_foreign_key(
        "auth_user_devices_ibfk_1",
        "auth_user_devices",
        "auth_users",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(
        "unique_user_device_fingerprint", "auth_user_devices", type_="unique"
    )
    op.drop_index(
        op.f("ix_auth_user_devices_os_version"), table_name="auth_user_devices"
    )
    op.drop_index(op.f("ix_auth_user_devices_os_name"), table_name="auth_user_devices")
    op.drop_index(
        op.f("ix_auth_user_devices_device_fingerprint"), table_name="auth_user_devices"
    )
    op.create_index(
        "uq_user_device",
        "auth_user_devices",
        ["user_id", "os_name", "os_version", "device_type"],
        unique=True,
    )
    op.create_index(
        "ix_auth_user_devices_ip_address",
        "auth_user_devices",
        ["ip_address"],
        unique=False,
    )
    op.alter_column(
        "auth_user_devices",
        "is_bot",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "auth_user_devices",
        "is_pc",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "auth_user_devices",
        "is_tablet",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "auth_user_devices",
        "is_mobile",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.drop_column("auth_user_devices", "device_fingerprint")
    # ### end Alembic commands ###
