"""mmdb tracker

Revision ID: 775d494cf03c
Revises: ccb22fa34d8d
Create Date: 2025-05-15 21:56:01.309239

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects.postgresql import UUID as PG_UUID


# revision identifiers, used by Alembic.
revision: str = "775d494cf03c"
down_revision: Union[str, None] = "ccb22fa34d8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_audit_logs",
        "event",
        existing_type=mysql.ENUM(
            "LOGIN",
            "PASSWORD_CHANGE",
            "PASSWORD_RESET",
            "CREATE_ACCOUNT",
            "REQUEST_VERIFICATION",
            "UPDATE_ACCOUNT",
            "REQUEST_MAGIC_LINK",
            "MAIL_ERROR",
            "HARD_DELETE",
            "DELETE_USER",
            "DELETE_SELF",
        ),
        type_=sa.Enum(
            "LOGIN",
            "PASSWORD_CHANGE",
            "PASSWORD_RESET",
            "CREATE_ACCOUNT",
            "REQUEST_VERIFICATION",
            "UPDATE_ACCOUNT",
            "REQUEST_MAGIC_LINK",
            "MAIL_ERROR",
            "DELETE_USER",
            "DELETE_SELF",
            "HARD_DELETE",
            name="auditlogeventenum",
        ),
        nullable=False,
    )
    op.create_table(
        "auth_mmdb_tracker",
        sa.Column(
            "id",
            sa.String(36) if op.get_context().dialect.name == "mysql" else PG_UUID,
            primary_key=True,
            index=True,
        ),
        sa.Column(
            "created_at", sa.DateTime, nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at",
            sa.DateTime,
            nullable=False,
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auth_audit_logs",
        "event",
        existing_type=sa.Enum(
            "LOGIN",
            "PASSWORD_CHANGE",
            "PASSWORD_RESET",
            "CREATE_ACCOUNT",
            "REQUEST_VERIFICATION",
            "UPDATE_ACCOUNT",
            "REQUEST_MAGIC_LINK",
            "MAIL_ERROR",
            "DELETE_USER",
            "DELETE_SELF",
            "HARD_DELETE",
            name="auditlogeventenum",
        ),
        type_=mysql.ENUM(
            "LOGIN",
            "PASSWORD_CHANGE",
            "PASSWORD_RESET",
            "CREATE_ACCOUNT",
            "REQUEST_VERIFICATION",
            "UPDATE_ACCOUNT",
            "REQUEST_MAGIC_LINK",
            "MAIL_ERROR",
            "HARD_DELETE",
            "DELETE_USER",
            "DELETE_SELF",
        ),
        nullable=True,
    )

    op.drop_table("auth_mmdb_tracker")
