"""user devices schema

Revision ID: c64651f96f13
Revises: 8fdba9de3301
Create Date: 2025-05-08 14:50:21.214664

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "c64651f96f13"
down_revision: Union[str, None] = "8fdba9de3301"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_auth_audit_logs_id", table_name="auth_audit_logs")
    op.create_index(
        op.f("ix_auth_totp_devices_confirmed"),
        "auth_totp_devices",
        ["confirmed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_user_attributes_id"), "auth_user_attributes", ["id"], unique=False
    )
    op.add_column(
        "auth_user_devices",
        sa.Column("user_agent_string", sa.String(length=500), nullable=False),
    )
    op.add_column(
        "auth_user_devices", sa.Column("os_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "auth_user_devices",
        sa.Column("os_version", sa.String(length=50), nullable=True),
    )
    op.add_column(
        "auth_user_devices",
        sa.Column("device_type", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "auth_user_devices", sa.Column("is_mobile", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "auth_user_devices", sa.Column("is_tablet", sa.Boolean(), nullable=True)
    )
    op.add_column("auth_user_devices", sa.Column("is_pc", sa.Boolean(), nullable=True))
    op.add_column("auth_user_devices", sa.Column("is_bot", sa.Boolean(), nullable=True))
    op.alter_column(
        "auth_user_devices",
        "ip_address",
        existing_type=mysql.VARCHAR(length=30),
        type_=sa.String(length=45),
        existing_nullable=False,
    )
    op.drop_index("ix_device_ip_address", table_name="auth_user_devices")
    op.drop_index("ix_device_last_used", table_name="auth_user_devices")
    op.drop_index("ix_device_user_id", table_name="auth_user_devices")
    op.create_index(
        op.f("ix_auth_user_devices_user_agent_string"),
        "auth_user_devices",
        ["user_agent_string"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_device",
        "auth_user_devices",
        ["user_id", "os_name", "os_version", "device_type"],
    )
    op.drop_column("auth_user_devices", "user_agent")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_user_devices",
        sa.Column("user_agent", mysql.VARCHAR(length=128), nullable=True),
    )
    op.drop_constraint("uq_user_device", "auth_user_devices", type_="unique")
    op.drop_index(
        op.f("ix_auth_user_devices_user_agent_string"), table_name="auth_user_devices"
    )
    op.create_index("ix_device_user_id", "auth_user_devices", ["user_id"], unique=False)
    op.create_index(
        "ix_device_last_used", "auth_user_devices", ["last_used"], unique=False
    )
    op.create_index(
        "ix_device_ip_address", "auth_user_devices", ["ip_address"], unique=False
    )
    op.alter_column(
        "auth_user_devices",
        "ip_address",
        existing_type=sa.String(length=45),
        type_=mysql.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.drop_column("auth_user_devices", "is_bot")
    op.drop_column("auth_user_devices", "is_pc")
    op.drop_column("auth_user_devices", "is_tablet")
    op.drop_column("auth_user_devices", "is_mobile")
    op.drop_column("auth_user_devices", "device_type")
    op.drop_column("auth_user_devices", "os_version")
    op.drop_column("auth_user_devices", "os_name")
    op.drop_column("auth_user_devices", "user_agent_string")
    op.drop_index(op.f("ix_auth_user_attributes_id"), table_name="auth_user_attributes")
    op.drop_index(
        op.f("ix_auth_totp_devices_confirmed"), table_name="auth_totp_devices"
    )
    op.create_index("ix_auth_audit_logs_id", "auth_audit_logs", ["id"], unique=False)
    # ### end Alembic commands ###
