"""delete orphan refresh tokens

Revision ID: cf2be8cec6a9
Revises: 31d01c97580a
Create Date: 2025-05-10 13:32:44.807070

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf2be8cec6a9"
down_revision: Union[str, None] = "31d01c97580a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "auth_refresh_tokens_ibfk_1", "auth_refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "auth_refresh_tokens",
        "auth_users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "auth_refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        "auth_refresh_tokens_ibfk_1",
        "auth_refresh_tokens",
        "auth_users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
